# Pandas Review

Siny P Raphel

## Importing pandas

### Getting started and checking your pandas setup

Difficulty: *easy* 

**1.** Import pandas under the alias `pd`.

In [1]:
import pandas as pd

**2.** Print the version of pandas that has been imported.

In [2]:
pd.__version__

'1.4.2'

**3.** Print out all the *version* information of the libraries that are required by the pandas library.

In [204]:
pd.show_versions()


INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.8.8.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 126 Stepping 5, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United States.1252

pandas           : 1.4.2
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 61.2.0
Cython           : 0.29.28
pytest           : 7.1.1
hypothesis       : None
sphinx           : 4.4.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : 4.8.0
html5lib         : 1.1
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.3.0
pandas_datareader: None
bs4              : 4.11.1
bottleneck       : 1.3.4


## DataFrame basics

### A few of the fundamental routines for selecting, sorting, adding and aggregating data in DataFrames

Difficulty: *easy*

Note: remember to import numpy using:
```python
import numpy as np
```

Consider the following Python dictionary `data` and Python list `labels`:

``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```
(This is just some meaningless data I made up with the theme of animals and trips to a vet.)

**4.** Create a DataFrame `df` from this dictionary `data` which has the index `labels`.

In [107]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index=labels)

**5.** Display a summary of the basic information about this DataFrame and its data (*hint: there is a single method that can be called on the DataFrame*).

In [433]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   animal    10 non-null     object 
 1   age       8 non-null      float64
 2   visits    10 non-null     int64  
 3   priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes


In [6]:
df.describe(include='all')

animal       age     visits priority
count      10  8.000000  10.000000       10
unique      3       NaN        NaN        2
top       cat       NaN        NaN       no
freq        4       NaN        NaN        6
mean      NaN  3.437500   1.900000      NaN
std       NaN  2.007797   0.875595      NaN
min       NaN  0.500000   1.000000      NaN
25%       NaN  2.375000   1.000000      NaN
50%       NaN  3.000000   2.000000      NaN
75%       NaN  4.625000   2.750000      NaN
max       NaN  7.000000   3.000000      NaN

**6.** Return the first 3 rows of the DataFrame `df`.

In [7]:
df.head(3)

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

**7.** Select just the 'animal' and 'age' columns from the DataFrame `df`.

In [109]:
# df.iloc[:,[0,1]]
# df.loc[:,['animal', 'age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

In [8]:
df[['animal', 'age']]

animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

**8.** Select the data in rows `[3, 4, 8]` *and* in columns `['animal', 'age']`.

In [12]:
df.iloc[[3,4,8], [0,1]]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

In [115]:
df.loc[df.index[[3,4,8]], ['animal', 'age']]

animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

**9.** Select only the rows where the number of visits is greater than 3.

In [13]:
df[df.visits>3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

**10.** Select the rows where the age is missing, i.e. it is `NaN`.

In [116]:
df.age.isna().sum()

2

In [15]:
df[df.age.isna()]

animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

**11.** Select the rows where the animal is a cat *and* the age is less than 3.

In [18]:
df[(df.animal == 'cat') & (df.age < 3)]

animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

**12.** Select the rows the age is between 2 and 4 (inclusive).

In [23]:
df[df.age.between(2,4)]

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

**13.** Change the age in row 'f' to 1.5.

In [27]:
df.loc['f', 'age']

2.0

In [117]:
df.loc['f', 'age'] = 1.5
df.loc['f', 'age']

1.5

**14.** Calculate the sum of all visits in `df` (i.e. find the total number of visits).

In [29]:
df.visits.sum()

19

**15.** Calculate the mean age for each different animal in `df`.

In [31]:
df.groupby('animal')['age'].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

**16.** Append a new row 'k' to `df` with your choice of values for each column. Then delete that row to return the original DataFrame.

In [118]:
df.loc['k'] =['dog', 5.5,2,'yes']

In [119]:
df.tail(1)

animal  age  visits priority
k    dog  5.5       2      yes

In [120]:
df.drop('k', axis=0, inplace=True)
df.tail(1)

animal  age  visits priority
j    dog  3.0       1       no

**17.** Count the number of each type of animal in `df`.

In [43]:
df.groupby('animal')['animal'].count()

animal
cat      4
dog      4
snake    2
Name: animal, dtype: int64

In [123]:
df['animal'].value_counts()

cat      4
dog      4
snake    2
Name: animal, dtype: int64

**18.** Sort `df` first by the values in the 'age' in *decending* order, then by the value in the 'visits' column in *ascending* order (so row `i` should be first, and row `d` should be last).

In [49]:
df.sort_values(by=['age', 'visits'], ascending=[False, True], inplace=True)
df

animal  age  visits priority
i    dog  7.0       2       no
e    dog  5.0       2       no
g  snake  4.5       1       no
j    dog  3.0       1       no
b    cat  3.0       3      yes
a    cat  2.5       1      yes
f    cat  1.5       3       no
c  snake  0.5       2       no
h    cat  NaN       1      yes
d    dog  NaN       3      yes

**19.** The 'priority' column contains the values 'yes' and 'no'. Replace this column with a column of boolean values: 'yes' should be `True` and 'no' should be `False`.

In [52]:
df.priority = df.priority == 'yes'
df.head(2)

animal  age  visits  priority
i    dog  7.0       2     False
e    dog  5.0       2     False

In [124]:
df.priority.map({'yes':True, 'no':False})
df.replace('yes',True)

a     True
b     True
c    False
d     True
e    False
f    False
g    False
h     True
i    False
j    False
Name: priority, dtype: bool

**20.** In the 'animal' column, change the 'snake' entries to 'python'.

In [54]:
df.animal[df.animal == 'snake']

g    snake
c    snake
Name: animal, dtype: object

In [55]:
df.animal[df.animal == 'snake'] = 'python'
# df.animal.replace('snake', 'python')

C:\Users\sinyp\AppData\Local\Temp\ipykernel_18204\2252203022.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.animal[df.animal == 'snake'] = 'python'


Series([], Name: animal, dtype: object)

In [56]:
df.animal[df.animal == 'python']

g    python
c    python
Name: animal, dtype: object

**21.** For each animal type and each number of visits, find the mean age. In other words, each row is an animal, each column is a number of visits and the values are the mean ages (*hint: use a pivot table*).

In [58]:
df.pivot_table(values='age', index='animal', columns='visits', fill_value=0)

visits    1    2     3
animal                
cat     2.5  0.0  2.25
dog     3.0  6.0  0.00
python  4.5  0.5  0.00

## DataFrames: beyond the basics

### Slightly trickier: you may need to combine two or more methods to get the right answer

Difficulty: *medium*

The previous section was tour through some basic but essential DataFrame operations. Below are some ways that you might need to cut your data, but for which there is no single "out of the box" method.

**22.** You have a DataFrame `df` with a column 'A' of integers. For example:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

How do you filter out rows which contain the same integer as the row immediately above?

You should be left with a column containing the following values:

```python
1, 2, 3, 4, 5, 6, 7
```

In [125]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
df.head(2)

A
0  1
1  2

In [230]:
out = [df.loc[0, 'A']]
for i in range(1,df.shape[0]):
#     print(df.loc[i, 'A'])
    if df.loc[i, 'A'] == df.loc[i-1, 'A']:
        pass
    else:
        out.append(df.loc[i, 'A'])

In [231]:
out

[1, 2, 3, 4, 5, 6, 7]

Alternate method without for loop

In [480]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
# Create a series for output with the first element inside
out = pd.Series(df.loc[0, 'A'], dtype='int')

In [481]:
# create another dataframe without first elemet in df and adding a duplicate of last element
df1 = pd.DataFrame({'A': [2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
df1.loc[df.shape[0],'A'] = df.iloc[-1, 0]


In [483]:
# Find the difference between two series and rows with -1 will give the output
out.append(df1.A[df.A.subtract(df1.A) ==-1])

C:\Users\sinyp\AppData\Local\Temp\ipykernel_18204\208634471.py:2: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out.append(df1.A[df.A.subtract(df1.A) ==-1])


0    1.0
0    2.0
2    3.0
3    4.0
4    5.0
7    6.0
8    7.0
dtype: float64

Alternate method but same approach as above

In [505]:
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
df['B'] = [2, 2, 3, 4, 5, 5, 5, 6, 7, 7, 7]
out=pd.Series(df.loc[0, 'A'])
out.append(df.B[df.B.subtract(df.A)!=0], ignore_index=True)


C:\Users\sinyp\AppData\Local\Temp\ipykernel_18204\1115210853.py:4: FutureWarning: The series.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  out.append(df.B[df.B.subtract(df.A)!=0], ignore_index=True)


0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

Method by Ashish

In [132]:
df.loc[df.A.shift(1) != df.A]

A
0  1
1  2
3  3
4  4
5  5
8  6
9  7

**23.** Given a DataFrame of numeric values, say
```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # a 5x3 frame of float values
```

how do you subtract the row mean from each element in the row?

In [73]:
df = pd.DataFrame(np.random.random(size=(5, 3)))
df

0         1         2
0  0.942925  0.744310  0.661738
1  0.617186  0.414746  0.560245
2  0.342595  0.149303  0.004693
3  0.387781  0.635878  0.540594
4  0.131206  0.641942  0.853644

In [78]:
df.mean(axis=1)

0    0.782991
1    0.530725
2    0.165530
3    0.521418
4    0.542264
dtype: float64

In [81]:
df.subtract(df.mean(axis=1), axis=0)

0         1         2
0  0.159934 -0.038681 -0.121253
1  0.086460 -0.115979  0.029519
2  0.177065 -0.016227 -0.160837
3 -0.133636  0.114460  0.019176
4 -0.411058  0.099678  0.311380

**24.** Suppose you have DataFrame with 10 columns of real numbers, for example:

```python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
Which column of numbers has the smallest sum?  Return that column's label.

In [82]:
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
df

a         b         c         d         e         f         g  \
0  0.323162  0.933944  0.009579  0.903680  0.494004  0.968282  0.834283   
1  0.655625  0.245985  0.743663  0.674865  0.785620  0.440060  0.865273   
2  0.122333  0.052424  0.731217  0.947845  0.772677  0.055935  0.744988   
3  0.914688  0.030732  0.610119  0.544922  0.538925  0.787177  0.366318   
4  0.516128  0.205488  0.791892  0.863934  0.501115  0.260672  0.665232   

          h         i         j  
0  0.845139  0.377823  0.066430  
1  0.148384  0.210907  0.698103  
2  0.659557  0.960929  0.908821  
3  0.104381  0.500564  0.827824  
4  0.116269  0.834844  0.971347

In [89]:
sum_array = df.sum()
sum_array.idxmin()

'b'

**25.** How do you count how many unique rows a DataFrame has (i.e. ignore all rows that are duplicates)? As input, use a DataFrame of zeros and ones with 10 rows and 3 columns.

```python
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))
```

In [94]:
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))


In [93]:
df.drop_duplicates().shape[0]

5

The next three puzzles are slightly harder.


**26.** In the cell below, you have a DataFrame `df` that consists of 10 columns of floating-point numbers. Exactly 5 entries in each row are NaN values. 

For each row of the DataFrame, find the *column* which contains the *third* NaN value.

You should return a Series of column labels: `e, c, d, h, d`

In [509]:
nan = np.nan

data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)

# write a solution to the question here

In [191]:
for i in range(df.shape[0]):
    print(df.loc[i][df.loc[i].isna()].index[2])

e
c
d
h
d


Alternate method without loop

In [512]:
df.isna().cumsum(axis=1)

a  b  c  d  e  f  g  h  i  j
0  0  1  2  2  3  3  3  3  4  5
1  1  2  3  3  3  4  5  5  5  5
2  1  2  2  3  3  3  4  5  5  5
3  0  1  2  2  2  2  2  3  4  5
4  1  2  2  3  3  4  4  5  5  5

In [513]:
 (df.isna().cumsum(axis=1) == 3)

a      b      c      d      e      f      g      h      i      j
0  False  False  False  False   True   True   True   True  False  False
1  False  False   True   True   True  False  False  False  False  False
2  False  False  False   True   True   True  False  False  False  False
3  False  False  False  False  False  False  False   True  False  False
4  False  False  False   True   True  False  False  False  False  False

In [205]:
 (df.isna().cumsum(axis=1) == 3).idxmax(axis=1)


0    e
1    c
2    d
3    h
4    d
dtype: object

**27.** A DataFrame has a column of groups 'grps' and and column of integer values 'vals': 

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
For each *group*, find the sum of the three greatest values. You should end up with the answer as follows:
```
grps
a    409
b    156
c    345
```

In [133]:
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'), 
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})



In [114]:
grps = df.groupby('grps')
out = pd.Series(dtype='float')
for grp, grp_df in grps:
    out[grp] = grp_df.sort_values(by='vals', ascending=False).iloc[:3, 1].sum()


In [115]:
out

a    409
b    156
c    345
dtype: int64

Alternate

In [135]:
grps = df.groupby('grps')
out = pd.Series(dtype='float')
for grp, grp_df in grps:
    out[grp] = grp_df['vals'].nlargest(3).sum()
out

a    409
b    156
c    345
dtype: int64

**28.** The DataFrame `df` constructed below has two integer columns 'A' and 'B'. The values in 'A' are between 1 and 100 (inclusive). 

For each group of 10 consecutive integers in 'A' (i.e. `(0, 10]`, `(10, 20]`, ...), calculate the sum of the corresponding values in column 'B'.

The answer should be a Series as follows:

```
A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
```

In [136]:
df = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])


In [135]:
# df[df.A.between(0, 10)]
out = pd.Series(dtype=int)
begin = 1
for i in range(10,101, 10):
    out[f"({begin-1}, {i}]"] = df[df.A.between(begin, i)]['B'].sum() #  
    begin = i+1
    

In [136]:
out

(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
dtype: int64

Alternate way

In [138]:
bins = pd.cut(df.A, [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

In [140]:
df.groupby(bins)['B'].sum()

A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
Name: B, dtype: int32

## DataFrames: harder problems 

### These might require a bit of thinking outside the box...

...but all are solvable using just the usual pandas/NumPy methods (and so avoid using explicit `for` loops).

Difficulty: *hard*

**29.** Consider a DataFrame `df` where there is an integer column 'X':
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```
For each value, count the difference back to the previous zero (or the start of the Series, whichever is closer). These values should therefore be 

```
[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
```

Make this a new column 'Y'.

In [311]:
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
df

X
0  7
1  2
2  0
3  3
4  4
5  2
6  5
7  0
8  3
9  4

In [312]:
df[df.X == 0]


X
2  0
7  0

**30.** Consider the DataFrame constructed below which contains rows and columns of numerical data. 

Create a list of the column-row index locations of the 3 largest values in this DataFrame. In this case, the answer should be:
```
[(5, 7), (6, 4), (2, 5)]
```

In [139]:
df = pd.DataFrame(np.random.RandomState(30).randint(1, 101, size=(8, 8)))
df

0   1   2   3   4   5   6   7
0  38  38  46  46  13  24   3  54
1  18  47   4  42   8  66  50  46
2  62  36  19  19  77  17   7  63
3  28  47  46  65  63  12  16  24
4  14  51  34  56  29  59  92  79
5  58  76  96  45  38  76  58  40
6  10  34  48  40  37  23  41  26
7  55  70  91  27  79  92  20  31

In [149]:
out[values] = df.max()#.sort_values(ascending=False)

0    62
1    76
2    96
3    65
4    79
5    92
6    92
7    79
dtype: int32

In [148]:
out[] = df.idxmax()

0    2
1    5
2    5
3    3
4    7
5    7
6    4
7    4
dtype: int64

**31.** You are given the DataFrame below with a column of group IDs, 'grps', and a column of corresponding integer values, 'vals'.

```python
df = pd.DataFrame({"vals": np.random.RandomState(31).randint(-30, 30, size=15), 
                   "grps": np.random.RandomState(31).choice(["A", "B"], 15)})
```

Create a new column 'patched_values' which contains the same values as the 'vals' any negative values in 'vals' with the group mean:

```
    vals grps  patched_vals
0    -12    A          13.6
1     -7    B          28.0
2    -14    A          13.6
3      4    A           4.0
4     -7    A          13.6
5     28    B          28.0
6     -2    A          13.6
7     -1    A          13.6
8      8    A           8.0
9     -2    B          28.0
10    28    A          28.0
11    12    A          12.0
12    16    A          16.0
13   -24    A          13.6
14   -12    A          13.6
```

**32.** Implement a rolling mean over groups with window size 3, which ignores NaN value. For example consider the following DataFrame:

```python
>>> df = pd.DataFrame({'group': list('aabbabbbabab'),
                       'value': [1, 2, 3, np.nan, 2, 3, np.nan, 1, 7, 3, np.nan, 8]})
>>> df
   group  value
0      a    1.0
1      a    2.0
2      b    3.0
3      b    NaN
4      a    2.0
5      b    3.0
6      b    NaN
7      b    1.0
8      a    7.0
9      b    3.0
10     a    NaN
11     b    8.0
```
The goal is to compute the Series:

```
0     1.000000
1     1.500000
2     3.000000
3     3.000000
4     1.666667
5     3.000000
6     3.000000
7     2.000000
8     3.666667
9     2.000000
10    4.500000
11    4.000000
```
E.g. the first window of size three for group 'b' has values 3.0, NaN and 3.0 and occurs at row index 5. Instead of being NaN the value in the new column at this row index should be 3.0 (just the two non-NaN values are used to compute the mean (3+3)/2)

## Series and DatetimeIndex

### Exercises for creating and manipulating Series with datetime data

Difficulty: *easy/medium*

pandas is fantastic for working with dates and times. These puzzles explore some of this functionality.


**33.** Create a DatetimeIndex that contains each business day of 2015 and use it to index a Series of random numbers. Let's call this Series `s`.

In [141]:
dates = pd.date_range('2015-01-01', '2015-12-31', freq='B')


In [321]:
len(dates)

261

In [142]:
s= pd.Series(index=dates, data= np.random.randint(1, 500, len(dates)))

**34.** Find the sum of the values in `s` for every Wednesday.

In [348]:
s[s.index.weekday == 2].sum()

14616

**35.** For each calendar month in `s`, find the mean of values.

In [145]:
s.groupby(s.index.month).mean()

1     260.181818
2     210.900000
3     194.136364
4     246.681818
5     223.619048
6     228.772727
7     246.826087
8     290.761905
9     253.863636
10    252.863636
11    228.904762
12    273.260870
dtype: float64

Alternate

In [144]:
s.resample('M').mean()

2015-01-31    260.181818
2015-02-28    210.900000
2015-03-31    194.136364
2015-04-30    246.681818
2015-05-31    223.619048
2015-06-30    228.772727
2015-07-31    246.826087
2015-08-31    290.761905
2015-09-30    253.863636
2015-10-31    252.863636
2015-11-30    228.904762
2015-12-31    273.260870
Freq: M, dtype: float64

**36.** For each group of four consecutive calendar months in `s`, find the date on which the highest value occurred.

In [353]:
s.groupby(s.index.quarter).idxmax()

1   2015-01-13
2   2015-04-22
3   2015-09-07
4   2015-11-20
dtype: datetime64[ns]

Alternate

In [147]:
s.groupby(pd.Grouper(freq='4M')).idxmax()

2015-01-31   2015-01-14
2015-05-31   2015-05-11
2015-09-30   2015-09-07
2016-01-31   2015-10-08
Freq: 4M, dtype: datetime64[ns]

**37.** Create a DateTimeIndex consisting of the third Thursday in each month for the years 2015 and 2016.

In [6]:
from datetime import timedelta as td

In [16]:
start_date = '2015-01-01'
for end_date in pd.date_range(start_date, '2016-12-31', freq='M'): # traverse thru end dates of each month
    # all the thursdays of the given range is returned and only the third thursday is printed
    print(pd.date_range(start_date, end_date, freq='W-THU')[2])
    start_date = end_date + td(days=1) # find start date by adding one day to the end date

2015-01-15 00:00:00
2015-02-19 00:00:00
2015-03-19 00:00:00
2015-04-16 00:00:00
2015-05-21 00:00:00
2015-06-18 00:00:00
2015-07-16 00:00:00
2015-08-20 00:00:00
2015-09-17 00:00:00
2015-10-15 00:00:00
2015-11-19 00:00:00
2015-12-17 00:00:00
2016-01-21 00:00:00
2016-02-18 00:00:00
2016-03-17 00:00:00
2016-04-21 00:00:00
2016-05-19 00:00:00
2016-06-16 00:00:00
2016-07-21 00:00:00
2016-08-18 00:00:00
2016-09-15 00:00:00
2016-10-20 00:00:00
2016-11-17 00:00:00
2016-12-15 00:00:00


Alternate

In [149]:
pd.date_range('2015-01-01', '2016-12-31', freq='WOM-3THU')

DatetimeIndex(['2015-01-15', '2015-02-19', '2015-03-19', '2015-04-16',
               '2015-05-21', '2015-06-18', '2015-07-16', '2015-08-20',
               '2015-09-17', '2015-10-15', '2015-11-19', '2015-12-17',
               '2016-01-21', '2016-02-18', '2016-03-17', '2016-04-21',
               '2016-05-19', '2016-06-16', '2016-07-21', '2016-08-18',
               '2016-09-15', '2016-10-20', '2016-11-17', '2016-12-15'],
              dtype='datetime64[ns]', freq='WOM-3THU')

Below is not the answer. just for future reference

In [374]:
# return all thursdays in three week interval
pd.date_range('2015-01-15', '2016-12-31', freq='3W-THU')

DatetimeIndex(['2015-01-15', '2015-02-05', '2015-02-26', '2015-03-19',
               '2015-04-09', '2015-04-30', '2015-05-21', '2015-06-11',
               '2015-07-02', '2015-07-23', '2015-08-13', '2015-09-03',
               '2015-09-24', '2015-10-15', '2015-11-05', '2015-11-26',
               '2015-12-17', '2016-01-07', '2016-01-28', '2016-02-18',
               '2016-03-10', '2016-03-31', '2016-04-21', '2016-05-12',
               '2016-06-02', '2016-06-23', '2016-07-14', '2016-08-04',
               '2016-08-25', '2016-09-15', '2016-10-06', '2016-10-27',
               '2016-11-17', '2016-12-08', '2016-12-29'],
              dtype='datetime64[ns]', freq='3W-THU')

## Cleaning Data

### Making a DataFrame easier to work with

Difficulty: *easy/medium*

It happens all the time: someone gives you data containing malformed strings, Python, lists and missing data. How do you tidy it up so you can get on with the analysis?

Take this monstrosity as the DataFrame to use in the following puzzles:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})
```
Formatted, it looks like this:

```
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
```


(It's some flight data I made up; it's not meant to be accurate in any way.)


In [150]:
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm', 
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )', 
                               '12. Air France', '"Swiss Air"']})

df=df.convert_dtypes(convert_integer=True) # avoids issues of value converting to float when replacing NANs flight number

In [376]:
df.head(2)

From_To  FlightNumber RecentDelays            Airline
0  LoNDon_paris       10045.0     [23, 47]             KLM(!)
1  MAdrid_miLAN           NaN           []  <Air France> (12)

**38.** Some values in the the **FlightNumber** column are missing (they are `NaN`). These numbers are meant to increase by 10 with each row so 10055 and 10075 need to be put in place. Modify `df` to fill in these missing numbers and make the column an integer column (instead of a float column).

In [69]:
for ix in df[df.FlightNumber.isna()].index: #traverse through index of missing flight values
    df.iloc[ix, 1] = df.iloc[ix-1, 1] +10


In [70]:
df.iloc[1]

From_To              MAdrid_miLAN
FlightNumber                10055
RecentDelays                   []
Airline         <Air France> (12)
Name: 1, dtype: object

Alternate method

In [393]:
# df.FlightNumber[df.FlightNumber.isna()] = [10055, 10075]

C:\Users\sinyp\AppData\Local\Temp\ipykernel_18204\4075617207.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.FlightNumber[df.FlightNumber.isna()] = [10055, 10075]


In [71]:
df

From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10045      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"

Alternate(Ashish)

**39.** The **From\_To** column would be better as two separate columns! Split each string on the underscore delimiter `_` to give a new temporary DataFrame called 'temp' with the correct values. Assign the correct column names 'From' and 'To' to this temporary DataFrame. 

In [72]:
temp = df.copy()
temp['From'] = temp.From_To.str.split('_', expand=True)[0]
temp['To'] = temp.From_To.str.split('_', expand=True)[1]
temp

From_To  FlightNumber  RecentDelays              Airline  \
0      LoNDon_paris         10045      [23, 47]               KLM(!)   
1      MAdrid_miLAN         10055            []    <Air France> (12)   
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )   
3    Budapest_PaRis         10075          [13]       12. Air France   
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"   

       From         To  
0    LoNDon      paris  
1    MAdrid      miLAN  
2    londON  StockhOlm  
3  Budapest      PaRis  
4  Brussels     londOn

**40.** Notice how the capitalisation of the city names is all mixed up in this temporary DataFrame 'temp'. Standardise the strings so that only the first letter is uppercase (e.g. "londON" should become "London".)

In [73]:
temp.From = temp.From.str.capitalize()
temp.To = temp.To.str.capitalize()

In [74]:
temp

From_To  FlightNumber  RecentDelays              Airline  \
0      LoNDon_paris         10045      [23, 47]               KLM(!)   
1      MAdrid_miLAN         10055            []    <Air France> (12)   
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )   
3    Budapest_PaRis         10075          [13]       12. Air France   
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"   

       From         To  
0    London      Paris  
1    Madrid      Milan  
2    London  Stockholm  
3  Budapest      Paris  
4  Brussels     London

**41.** Delete the **From_To** column from `df` and attach the temporary DataFrame 'temp' from the previous questions.

In [75]:
temp.drop('From_To', inplace=True, axis=1)

**42**. In the **Airline** column, you can see some extra puctuation and symbols have appeared around the airline names. Pull out just the airline name. E.g. `'(British Airways. )'` should become `'British Airways'`.

In [76]:
temp.Airline = temp.Airline.str.replace('[<>!\(\).\"\d]', '', regex=True)

In [77]:
temp

FlightNumber  RecentDelays           Airline      From         To
0         10045      [23, 47]               KLM    London      Paris
1         10055            []       Air France     Madrid      Milan
2         10065  [24, 43, 87]  British Airways     London  Stockholm
3         10075          [13]        Air France  Budapest      Paris
4         10085      [67, 32]         Swiss Air  Brussels     London

In [ ]:
temp.Airline.str.

**43**. In the RecentDelays column, the values have been entered into the DataFrame as a list. We would like each first value in its own column, each second value in its own column, and so on. If there isn't an Nth value, the value should be NaN.

Expand the Series of lists into a DataFrame named `delays`, rename the columns `delay_1`, `delay_2`, etc. and replace the unwanted RecentDelays column in `df` with `delays`.

In [95]:
delays = pd.DataFrame(temp.RecentDelays.to_list())
delay_names = []
for i in delays.columns:
    delay_names.append('delay_' + str(i))
delays.columns = delay_names

In [106]:
df.join(delays).drop('RecentDelays', axis=1)

From_To  FlightNumber              Airline  delay_0  delay_1  \
0      LoNDon_paris         10045               KLM(!)     23.0     47.0   
1      MAdrid_miLAN         10055    <Air France> (12)      NaN      NaN   
2  londON_StockhOlm         10065  (British Airways. )     24.0     43.0   
3    Budapest_PaRis         10075       12. Air France     13.0      NaN   
4   Brussels_londOn         10085          "Swiss Air"     67.0     32.0   

   delay_2  
0      NaN  
1      NaN  
2     87.0  
3      NaN  
4      NaN

The DataFrame should look much better now.
```
   FlightNumber          Airline      From         To  delay_1  delay_2  delay_3
0         10045              KLM    London      Paris     23.0     47.0      NaN
1         10055       Air France    Madrid      Milan      NaN      NaN      NaN
2         10065  British Airways    London  Stockholm     24.0     43.0     87.0
3         10075       Air France  Budapest      Paris     13.0      NaN      NaN
4         10085        Swiss Air  Brussels     London     67.0     32.0      NaN
```